import 'package:enough_mail_plus/enough_mail.dart';
import 'package:test/test.dart';

// cSpell:disable

/// Real-world MIME generated by mimetext on Linux (bare LF line endings).
/// Source: nostr-mail-js output.eml
/// This tests that enough_mail can parse non-RFC-5322-compliant MIME
/// that uses bare `\n` instead of `\r\n`.
void main() {
  group('MimeMessage with bare LF (nostr-mail-js output)', () {
    // This MIME was generated by mimetext 3.0.28 on Linux (node:os.EOL = '\n')
    const mimeWithBareLF = 'Date: Sun, 05 Apr 2026 22:33:05 +0000\n'
        'From: <test@nostr>\n'
        'To: <recipient@example.com>\n'
        'Message-ID: <l5cw0a8ejj@nostr>\n'
        'Subject: =?utf-8?B?bGllbg==?=\n'
        'MIME-Version: 1.0\n'
        'Content-Type: multipart/alternative; boundary=ht75jd93mzb\n'
        '\n'
        '--ht75jd93mzb\n'
        'Content-Type: text/plain; charset=UTF-8\n'
        'Content-Transfer-Encoding: 7bit\n'
        '\n'
        'https://nostrmail.org\n'
        '\n'
        '--ht75jd93mzb\n'
        'Content-Type: text/html; charset=UTF-8\n'
        'Content-Transfer-Encoding: 7bit\n'
        '\n'
        '<a href="https://nostrmail.org">https://nostrmail.org</a>\n'
        '\n'
        '--ht75jd93mzb--\n';

    test('parses headers with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);

      expect(message.decodeSubject(), 'lien',
          reason: 'RFC 2047 subject should be decoded');
      expect(message.decodeDate(), isNotNull,
          reason: 'Date header should be parsed');
      expect(message.decodeHeaderDateValue('date'), isA<DateTime>());
    });

    test('parses From address with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);
      final from = message.from;

      expect(from, isNotNull);
      expect(from, hasLength(1));
      expect(from![0].email, 'test@nostr');
    });

    test('parses multipart/alternative structure with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);

      expect(message.mediaType.isMultipart, isTrue);
      expect(message.parts, isNotNull);
      expect(message.parts, hasLength(2));
    });

    test('extracts plain text part with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);

      final plainText = message.decodeTextPlainPart();
      expect(plainText, isNotNull);
      expect(plainText, contains('https://nostrmail.org'));
    });

    test('extracts HTML part with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);

      final html = message.decodeTextHtmlPart();
      expect(html, isNotNull);
      expect(html, contains('<a href="https://nostrmail.org">'));
    });

    test('parses boundary correctly with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);
      final contentType = message.getHeaderContentType();

      expect(contentType, isNotNull);
      expect(contentType!.boundary, 'ht75jd93mzb');
    });

    test('roundtrip: render and re-parse with bare LF', () {
      final message = MimeMessage.parseFromText(mimeWithBareLF);
      final rendered = message.renderMessage();

      // After re-parsing, all data should be preserved
      final reParsed = MimeMessage.parseFromText(rendered);
      expect(reParsed.decodeSubject(), 'lien');
      expect(reParsed.decodeTextPlainPart(), contains('https://nostrmail.org'));
      expect(reParsed.decodeTextHtmlPart(),
          contains('<a href="https://nostrmail.org">'));
    });
  });
}
