name: enough_mail
description: "enough_mail - IMAP, POP3, SMTP email library with high/low-level APIs and MIME parsing"
version: 2.2.4
repository: https://github.com/Enough-Software/enough_mail
topics:
  - email
  - imap
  - pop3
  - smtp
  - mime


environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  basic_utils: ^5.8.2
  collection: ^1.19.1
  crypto: ^3.0.7
  # encrypt: ^5.0.3
  encrypter_plus: ^5.1.0
  enough_convert: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.11.0
  pointycastle: ^4.0.0
  synchronized: ^3.4.0
  xml: ">=6.0.0 <8.0.0"

dev_dependencies:
  build_runner: ^2.15.0
  dart_code_linter: ^4.0.3
  flutter_lints: ^6.0.0
  json_serializable: ^6.13.2
  lints: ^6.1.0
  test: ^1.31.1
  timezone: ^0.11.0
